### PR TITLE
English translation of README.md

### PR DESCRIPTION
**Pull request by marysieek**
I am not a native Russian speaker, therefore feel free to correct this README file.

### CODE REVIEW

**Comment by stereodenis** [comment]
@marysieek could you rebase your branch?

**Comment by marysieek** [comment]
@stereodenis done

**Comment by marysieek** [comment]
@stereodenis @7even created 2 separate readme files and fixed gitter badge

**Comment by 7even** [comment]
@marysieek Thank you. I'll try to get to it as soon as I can.

**Comment by marysieek** [comment]
спс )

**Comment by 7even** [comment]
@marysieek I went through the file and fixed some grammar mistakes, then merged it into master. Thank you. Sorry it took so long :)

**Pull request merged**
